<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Matemática e Estatística Aplicada Para Data Science, Machine Learning e IA</font>
## <font color='blue'>Lista de Exercícios 7</font>
## <font color='blue'>Operações com Determinante e Matriz Inversa</font>

## Instalando e Carregando os Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
#!pip install -q -U watermark

In [2]:
# Imports
import numpy as np

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" 

Author: Data Science Academy



**Resolva os exercícios abaixo usando Linguagem Python. Faça pesquisa complementar se necessário.**

### Exercício 1: Cálculo de Determinante

Calcule o determinante da matriz 3x3 abaixo. 

In [4]:
dsa_matriz_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
print(dsa_matriz_1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
# Cálculo do determinante COM NumPy:(PRÓXIMO DE ZERO)
determinante = np.linalg.det(dsa_matriz_1)
print(f"o determinante: {determinante}.")

o determinante: 6.66133814775094e-16.


In [11]:
# Cálculo do determinante SEM NumPy:(= ZERO)
det1=1*(-3)-2*(-6)+3*(-3)
print(det1)

0


'''Conclusão:
O determinante correto da matriz 𝐴 deve ser zero, pois as linhas da matriz são linearmente dependentes (a terceira linha é a soma das duas primeiras). Se o NumPy retornou um valor muito pequeno ao invés de exatamente zero, isso se deve a erros numéricos inerentes à computação em ponto flutuante.'''

### Exercício 2: Matriz Inversa de uma Matriz 2x2

Crie uma função em Python que receba uma matriz 2x2 e retorne sua inversa. Não use o NumPy. Teste sua função com a seguinte matriz:

In [12]:
dsa_matriz_2 = [[4, 7], [2, 6]]

In [22]:
# SEM NUMPY:
def inverse_2x2(matrix):
    a, b = matrix[0][0], matrix[0][1]
    c, d = matrix[1][0], matrix[1][1]
    
    det = a*d - b*c
    
    if det == 0:
        raise ValueError("A matriz não tem inversa (determinante zero).")
    inverse_matrix = [[d / det, -b / det], 
                      [-c / det, a / det]]
    return print(f"A matriz inversa: \n {inverse_matrix}.")

A = [[4, 7], [2, 6]]
A_inv = inverse_2x2(A)


A matriz inversa: 
 [[0.6, -0.7], [-0.2, 0.4]].


In [23]:
# COM NUMPY:
A_inv = np.linalg.inv(A)  # Calcula a matriz inversa

print(f"A matriz inversa: \n{A_inv}.")

A matriz inversa: 
[[ 0.6 -0.7]
 [-0.2  0.4]].


### Exercício 3: Verificação de Determinante Zero

Verifique se o determinante da matriz 3x3 abaixo é zero e se a matriz tem inversa.

In [39]:
dsa_matriz_3 = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [40]:
matriz_3 = np.array ([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [41]:
determinante = np.linalg.det(matriz_3)

In [42]:
print(f"Determinante: {determinante}")

Determinante: 0.0


In [44]:
print("A matriz tem inversa." if determinante != 0 else "A matriz não tem inversa(determinante igual a zero).")

A matriz não tem inversa(determinante igual a zero).


In [29]:
import numpy as np

def verifica_determinante(c):
    det = np.linalg.det(c)  # Calcula o determinante da matriz
    if det == 0:
        raise ValueError("A matriz não tem inversa (determinante igual à zero).")

    print(f"O determinante da matriz\n {c} é {det}.")
    print(f"A matriz possui inversa.")

# Matriz corrigida (elementos separados por vírgulas)
c = np.array([[1, 2, 8], 
              [3, 5, 7], 
              [4, 6, 2]])

# Chama a função
verifica_determinante(c)

O determinante da matriz
 [[1 2 8]
 [3 5 7]
 [4 6 2]] é -4.0.
A matriz possui inversa.


### Exercício 4: Cálculo de Matriz Inversa com Numpy

Utilize a biblioteca Numpy para calcular a inversa de uma matriz 3x3. Considere esta matriz abaixo para o cálculo. Use try/except para tratar eventuais erros.

In [48]:
dsa_matriz_4 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

In [49]:
try:
    inversa = np.linalg.inv(dsa_matriz_4)
    print(f"Inversa:\n{inversa}")
except np.linalg.LinAlgError:
    print("A matriz não tem inversa.")


Inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [50]:
try:
    inversa = np.linalg.inv(matriz_3)
    print(f"Inversa:\n{inversa}")
except np.linalg.LinAlgError:
    print("A matriz não tem inversa.")

A matriz não tem inversa.


### Exercício 5: Determinante e Inversa de uma Matriz 4x4

Calcule o determinante e a inversa da matriz 4x4 abaixo, caso a inversa exista. 

In [51]:
dsa_matriz_5 = [[1, 0, 2, -1], [3, 0, 0, 5], [2, 1, 4, -3], [1, 0, 5, 0]]

In [52]:
def verifica_det(x):
    
    det = np.linalg.det(x)
    # Verifica se a matriz tem inversa
    if det == 0:
        raise ValueError("A matriz não tem inversa (determinante = zero).")        
    
    print(f"O determinante da matriz\n {x} é {det:.2f}.")
    print("A matriz possui inversa. O determinante é diferente de zero.")
    
    x_inv = np.linalg.inv(x)
    print(f"A matriz inversa é\n {x_inv}.")
x = np.array([[1, 0, 2, -1], [3, 0, 0, 5], [2, 1, 4, -3], [1, 0, 5, 0]])
verifica_det(x)

O determinante da matriz
 [[ 1  0  2 -1]
 [ 3  0  0  5]
 [ 2  1  4 -3]
 [ 1  0  5  0]] é 30.00.
A matriz possui inversa. O determinante é diferente de zero.
A matriz inversa é
 [[ 0.83333333  0.16666667  0.         -0.33333333]
 [-2.5         0.1         1.          0.2       ]
 [-0.16666667 -0.03333333  0.          0.26666667]
 [-0.5         0.1        -0.          0.2       ]].


In [53]:
try:
    deteminante= np.linalg.det(x)
    inversa = np.linalg.inv(x)
    print(f"Inversa:\n{inversa}")
except np.linalg.LinAlgError:
    print("A matriz não tem inversa.")
x = np.array([[1, 0, 2, -1], [3, 0, 0, 5], [2, 1, 4, -3], [1, 0, 5, 0]])    

Inversa:
[[ 0.83333333  0.16666667  0.         -0.33333333]
 [-2.5         0.1         1.          0.2       ]
 [-0.16666667 -0.03333333  0.          0.26666667]
 [-0.5         0.1        -0.          0.2       ]]


In [54]:
try:
    deteminante= np.linalg.det(matriz_3)
    inversa = np.linalg.inv(matriz_3)
    print(f"Inversa:\n{inversa}")
except np.linalg.LinAlgError:
    print("A matriz não tem inversa.")


A matriz não tem inversa.


In [55]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



In [56]:
%watermark -v -m

Python implementation: CPython
Python version       : 3.9.13
IPython version      : 7.31.1

Compiler    : GCC 11.2.0
OS          : Linux
Release     : 5.4.0-205-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit



In [57]:
%watermark --iversions

numpy: 1.20.1



## Fim