In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [2]:
# Imports
import numpy as np

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" 

Author: Data Science Academy



**Resolva os exercícios abaixo usando Linguagem Python. Faça pesquisa complementar se necessário.**

In [4]:
# Criando duas matrizes de exemplo
matriz1 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
matriz2 = [[5, 2, 8], [3, 1, 2], [7, 0, 2]]

In [5]:
print(matriz1)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]


In [6]:
type(matriz1)

list

In [7]:
print(matriz2)

[[5, 2, 8], [3, 1, 2], [7, 0, 2]]


In [8]:
type(matriz2)

list

###  Exercício 1: Soma de Matrizes

Escreva um programa em Python que soma duas matrizes de mesmo tamanho. As matrizes devem ser lidas como listas de listas e o resultado deve ser exibido na tela. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

**RESULTADO SEM O USO DO NUMPY**

In [9]:
matriz1 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

In [10]:
print(matriz1)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [11]:
type(matriz1)

numpy.ndarray

In [12]:
matriz2 = np.array([[5, 2, 8], [3, 1, 2], [7, 0, 2]])

In [13]:
print(matriz2)

[[5 2 8]
 [3 1 2]
 [7 0 2]]


In [14]:
type(matriz2)

numpy.ndarray

In [15]:
# Criando uma matriz resultado 3x3 preenchida com zeros
resultado = [[0, 0, 0] for _ in range(3)]

# Somando as matrizes
for i in range(3):  # Percorre as linhas
    for j in range(3):  # Percorre as colunas
        resultado[i][j] = matriz1[i][j] + matriz2[i][j]

soma = np.array(resultado)
print(soma)

[[ 6  4 11]
 [ 3  2  6]
 [12  6  2]]


**RESULTADO COM O USO DO NUMPY**

In [16]:
soma_np = matriz1 + matriz2
print(soma_np)

[[ 6  4 11]
 [ 3  2  6]
 [12  6  2]]


In [17]:
type(soma_np)

numpy.ndarray

** SOLUÇÃO APRESENTADA**

In [18]:
# Com NumPy - Versão 1 (mais simples de todas)
def dsa_soma_matrizes_v1(m1, m2):
    return np.array(m1) + np.array(m2)
dsa_soma_matrizes_v1(matriz1, matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

In [19]:
# Com NumPy - Versão 2
def dsa_soma_matrizes_v2(A, B):
    
    A_np = np.array(A)
    B_np = np.array(B)
    
    return A_np + B_np
dsa_soma_matrizes_v2(matriz1, matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

In [20]:
# Sem NumPy - Versão 3
def dsa_soma_matrizes_v3(m1, m2):
    
    # Verifica se as matrizes têm o mesmo número de linhas e colunas
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]):
        
        # Retorna uma mensagem de erro se as matrizes não tiverem o mesmo tamanho
        return "As matrizes devem ter o mesmo tamanho"  
    
    # Inicializa a matriz de resultado como uma lista vazia
    resultado = [] 
    
    # Loop através de cada linha da matriz
    for i in range(len(m1)):
        
        # Inicializa uma nova linha para a matriz de resultado
        linha = []  
        
        # Loop através de cada coluna da linha atual
        for j in range(len(m1[0])):
            
            # Soma os elementos correspondentes das duas matrizes e adiciona à linha
            linha.append(m1[i][j] + m2[i][j])  
        
        # Adiciona a linha recém-calculada à matriz de resultado
        resultado.append(linha)  
    
    # Retorna a matriz de resultado após somar todos os elementos
    return resultado  
dsa_soma_matrizes_v3(matriz1, matriz2)

[[6, 4, 11], [3, 2, 6], [12, 6, 2]]

In [21]:
# Sem NumPy - Versão 4 (mais complexa)
def dsa_soma_matrizes_v4(A, B):
    
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        
        return "Matrizes de tamanhos diferentes"
    
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
dsa_soma_matrizes_v3(matriz1, matriz2)

[[6, 4, 11], [3, 2, 6], [12, 6, 2]]

Exercício 2: Multiplicação de Matrizes
Implemente uma função em Python que multiplica duas matrizes. Verifique se as dimensões das matrizes são compatíveis para a multiplicação e retorne a matriz resultante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

**RESULTADO SEM NUMPY**

In [22]:
def multiplica_matrizes(A, B):
    # Número de linhas e colunas das matrizes
    linhas_A, colunas_A = len(A), len(A[0])
    linhas_B, colunas_B = len(B), len(B[0])

    # Verifica se a multiplicação é possível (número de colunas de A == número de linhas de B)
    if colunas_A != linhas_B:
        raise ValueError("Número de colunas de A deve ser igual ao número de linhas de B.")

    # Cria a matriz resultado com zeros (m x p)
    C = [[0] * colunas_B for _ in range(linhas_A)]

    # Multiplicação de matrizes
    for i in range(linhas_A):  # Percorre as linhas de A
        for j in range(colunas_B):  # Percorre as colunas de B
            for k in range(colunas_A):  # Percorre os elementos da linha de A e coluna de B
                C[i][j] += A[i][k] * B[k][j]

    return C

# Exemplo de uso
A = [[1, 2, 3], 
     [4, 5, 6]]

B = [[7, 8], 
     [9, 10], 
     [11, 12]]

C = np. array(multiplica_matrizes(A, B))

# Exibir resultado
for linha in C:
    print(linha)
type(C)

[58 64]
[139 154]


numpy.ndarray

**RESULTADO COM NUMPY**

In [23]:
def multiplica_matrizes(A, B):
    # Número de linhas e colunas das matrizes
    linhas_A, colunas_A = len(A), len(A[0])
    linhas_B, colunas_B = len(B), len(B[0])

    # Verifica se a multiplicação é possível (número de colunas de A == número de linhas de B)
    if colunas_A != linhas_B:
        raise ValueError("Número de colunas de A deve ser igual ao número de linhas de B.")
    return np.dot(A, B)

# Definição das matrizes
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

B = np.array([[7, 8], 
              [9, 10], 
              [11, 12]])

C = multiplica_matrizes(A, B)

# Exibir resultado
print(C)
type(C)

[[ 58  64]
 [139 154]]


numpy.ndarray

### Exercício 3: Transposição de Matriz

Crie um programa que calcula a transposta de uma matriz. A matriz deve ser inserida pelo usuário e o programa deve exibir a matriz transposta. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

**RESULTADO SEM NUMPY**

In [25]:
def ler_matriz():
    # Pedir número de linhas e colunas
    m = int(input("Digite o número de linhas: "))
    n = int(input("Digite o número de colunas: "))

    matriz = []  # Lista vazia para armazenar a matriz

    # Loop para preencher a matriz
    for i in range(m):
        linha = list(map(int, input(f"Digite os {n} elementos da linha {i+1}, separados por espaço: ").split()))
        while len(linha) != n:  # Verifica se o usuário digitou a quantidade correta de elementos
            print("Número incorreto de elementos! Tente novamente.")
            linha = list(map(int, input(f"Digite os {n} elementos da linha {i+1}, separados por espaço: ").split()))
        matriz.append(linha)

    return matriz

# Testando a função
matriz = ler_matriz()

# Exibindo a matriz formatada
print("\nMatriz digitada:")
for linha in matriz:
    print(linha)


Digite o número de linhas: 2
Digite o número de colunas: 3
Digite os 3 elementos da linha 1, separados por espaço: 1 2 3
Digite os 3 elementos da linha 2, separados por espaço: 4 5 6

Matriz digitada:
[1, 2, 3]
[4, 5, 6]


In [26]:
def transposta(matriz):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

AT = transposta(matriz)
# Exibir a matriz transposta
for linha in AT:
    print(linha)

[1, 4]
[2, 5]
[3, 6]


**RESULTADO COM NUMPY**

In [27]:
def ler_matriz():
    # Pedir número de linhas e colunas
    m = int(input("Digite o número de linhas: "))
    n = int(input("Digite o número de colunas: "))

    matriz = []  # Lista vazia para armazenar a matriz

    # Loop para preencher a matriz
    for i in range(m):
        linha = list(map(int, input(f"Digite os {n} elementos da linha {i+1}, separados por espaço: ").split()))
        while len(linha) != n:  # Verifica se o usuário digitou a quantidade correta de elementos
            print("Número incorreto de elementos! Tente novamente.")
            linha = list(map(int, input(f"Digite os {n} elementos da linha {i+1}, separados por espaço: ").split()))
        matriz.append(linha)

    return matriz

# Testando a função
matriz = ler_matriz()

# Exibindo a matriz formatada
print("\nMatriz digitada:")
for linha in matriz:
    print(linha)


Digite o número de linhas: 2 
Digite o número de colunas: 3
Digite os 3 elementos da linha 1, separados por espaço: 1 2 3
Digite os 3 elementos da linha 2, separados por espaço: 4 5 6

Matriz digitada:
[1, 2, 3]
[4, 5, 6]


In [28]:
matriz_np = np.array(matriz)
AT = matriz_np.T
print(AT)

[[1 4]
 [2 5]
 [3 6]]


**SOLUÇÃO APRESENTADA COM LIST COMPREHENSION SEM NUMPY**

In [29]:
# Sem NumPy
def dsa_transposicao_v2(matriz):
    
    return [[matriz[j][i] for j in range(len(matriz))] for i in range(len(matriz[0]))]
print(dsa_transposicao_v2(matriz))

[[1, 4], [2, 5], [3, 6]]


**Exercício 4: Traço de uma Matriz**

Desenvolva um script em Python que calcula o traço de uma matriz (soma dos elementos da diagonal principal). O programa deve funcionar para matrizes quadradas de qualquer tamanho. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

**RESULTADO SEM NUMPY**

In [34]:
def traco_matriz(A):
    # Verifica se a matriz é quadrada.
    if len(A) != len(A[0]):
        return "A matriz deve ser quadrada. O número de linhas deve ser igual ao número de colunas."
    
    
    # cria a variável soma vazia:
    soma = 0
                     
    # Percorre a diagonal principal.
    for i in range(len(A)):
            soma += A[i][i]
    
    return soma
        
A = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]]

B = [[1, 2, 3], 
     [4, 5, 6]]


print(f"O traço da matriz A é igual à {traco_matriz(A)}.")
print(f"Não é possivel calcular o traço da matriz B. {traco_matriz(B)}.")

O traço da matriz A é igual à 15.
Não é possivel calcular o traço da matriz B. A matriz deve ser quadrada. O número de linhas deve ser igual ao número de colunas..


**RESULTADO COM NUMPY**

In [33]:
def traco_matriz(A):
    # Verifica se a matriz é quadrada.
    if len(A) != len(A[0]):
        return "A matriz deve ser quadrada. O número de linhas deve ser igual ao número de colunas."
    
    return np.trace(A)
    
    return soma
        
A = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]]

B = [[1, 2, 3], 
     [4, 5, 6]]


print(f"O traço da matriz A é igual à {traco_matriz(A)}.")
print(f"Não é possivel calcular o traço da matriz B. {traco_matriz(B)}.")

O traço da matriz A é igual à 15.
Não é possivel calcular o traço da matriz B. A matriz deve ser quadrada. O número de linhas deve ser igual ao número de colunas..


***Exercício 5: Determinante de uma Matriz (Desafio)***

Escreva uma função que calcula o determinante de uma matriz quadrada. Utilize a recursividade ou o método de Laplace para calcular o determinante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

O determinante de uma matriz é um valor escalar que fornece informações importantes sobre a matriz. Ele é aplicável apenas a matrizes quadradas (matrizes com o mesmo número de linhas e colunas). O determinante tem várias interpretações e aplicações na matemática, particularmente em álgebra linear, análise e geometria.

Algumas das principais propriedades e interpretações do determinante são:

Interpretação Geométrica: Para matrizes 2x2 e 3x3, o determinante pode ser interpretado como a área (para matrizes 2x2) ou o volume (para matrizes 3x3) do paralelogramo ou paralelepípedo formado pelos vetores que compõem as linhas ou colunas da matriz.

Singularidade: Um determinante igual a zero indica que a matriz é singular (não invertível). Isso acontece quando as linhas ou colunas da matriz são linearmente dependentes, ou seja, uma linha ou coluna pode ser expressa como uma combinação linear das outras.

Transformações Lineares: Em termos de transformações lineares, o determinante de uma matriz que representa uma transformação linear indica se a transformação preserva, inverte ou deforma o espaço. Um determinante negativo indica que a orientação foi invertida.

Solução de Sistemas Lineares: O determinante é usado na regra de Cramer para resolver sistemas de equações lineares. Se o determinante da matriz dos coeficientes for diferente de zero, existe uma única solução para o sistema.

